name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  RUST_STABLE: stable
  RUST_NIGHTLY: nightly-2025-10-12

defaults:
  run:
    shell: bash

jobs:
  basics:
    name: basics
    runs-on: ubuntu-latest
    needs:
      - clippy
      - fmt
    steps:
      - run: exit 0

  build:
    name: build
    needs: basics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
      - uses: Swatinem/rust-cache@v2
      - name: build
        run: cargo build --verbose

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo +${{ env.RUST_NIGHTLY }} fmt --all --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy --all --tests --no-deps --all-features

  udeps:
    name: udeps
    needs: basics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
      - name: Install cargo-udeps
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps
      - uses: Swatinem/rust-cache@v2
      - name: udeps
        run: cargo +${{ env.RUST_NIGHTLY }} udeps --all-targets

  check-spelling:
    name: check-spelling
    needs: basics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
      - name: Install cargo-spellcheck
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-spellcheck
      - name: Run cargo-spellcheck
        run: |
          if ! cargo spellcheck --code 1 --cfg spellcheck.toml
          then
              echo ''
              echo ''
              echo 'If this is a Rust method/type/variable name, then you should'
              echo 'enclose it in backticks like this: `MyRustType`.'
              echo ''
              echo 'If this is a real word, then you can add it to spellcheck.dic'
              exit 1
          fi
      - name: Detect trailing whitespace
        run: |
          if grep --exclude-dir=.git --exclude-dir=target -rne '\s$' .
          then
              echo ''
              echo 'Please remove trailing whitespace from these lines.'
              exit 1
          fi

  # test:
  #   name: test
  #   needs: basics
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Install Rust ${{ env.RUST_STABLE }}
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: ${{ env.RUST_STABLE }}
  #     - name: Install cargo-nextest
  #       uses: taiki-e/install-action@v2
  #       with:
  #         tool: cargo-nextest
  #     - uses: Swatinem/rust-cache@v2
  #     - name: test
  #       run: cargo nextest run --all-features
